[workspace]
members = [
    "serde",
    "serde_derive",
    "serde_derive_internals",
    "serde_test",
    "test_suite",
]

[patch.crates-io]
failure = { git = "https://github.com/withoutboats/failure" }
